### ISSUE TITLE
Display profile pic of the logged user in the navbar

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/Hacktoberfest-Leaderboard#10]
Display the pfp with the name of the logged in user

**Comment by magmukendi** [comment]
I would like to work on this issue. Would you mind assigning it to me?

**Comment by ken1000minus7** [comment]
Sure @LeGrandMAG , good luck ! 😇

**Comment by Ishikasaraf20** [comment]
hey @ken1000minus7 can you assign this issue to me i can work on it

**Comment by ken1000minus7** [comment]
@Ishikasaraf20 thanks for your interest in contributing but this issue is already assigned 😅 For now, you can check out other issues or create new ones 😇

**Comment by magmukendi** [comment]
@ken1000minus7, I just created a pull request (#11).  Please check it out and let me know :)
