### ISSUE TITLE
The "view demo" link does not work as expected

### ISSUE THREAD

**Issue by magmukendi** [PEC-CSS/Hacktoberfest-Leaderboard#12]
I expected the view demo to redirect me to a live version of the project. But it just brought me back to the repository.

It will be great if you could have a live version of the site hosted either on Netlify or GitHub pages.

**Comment by ken1000minus7** [comment]
Yeah, the project is yet to be deployed. We'll deploy it soon on vercel 😇

**Comment by ken1000minus7** [comment]
The website has been deployed now on vercel, the link is in the description, not yet added in the readme though

**Comment by magmukendi** [comment]
Niiiiiiiiiiiiiiiiiiiiice! Thank you for letting me know :)
