### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/Hacktoberfest-Leaderboard#2]
Update the README according to the format used in other PEC-CSS repositories

**Comment by israelmitolu** [comment]
Hi @ken1000minus7 
Kindly assign this issue to me.

**Comment by ken1000minus7** [comment]
Sure @israelmitolu good luck ! 😇

**Comment by israelmitolu** [comment]
Hi @ken1000minus7 , I have just opened a PR. 
There are some things missing though:
- `License.MD` 
- `Contributing.MD`
- Link to the live website

I would love to work on them, also :)

**Comment by ken1000minus7** [comment]
Sure @israelmitolu , u can make a separate for them 😇

**Comment by israelmitolu** [comment]
Awesome, thanks.
